### PR TITLE
Added MPD formula

### PR DESCRIPTION
**Pull request by sergeihychko**
Added the MPD formula to the 2-regression.tex file.

### CODE REVIEW

**Comment by sergeihychko** [comment]
This was a pull request in reference to issue #124 .

**Comment by santiviquez** [comment]
Hi @sergeihychko, thank you for this contribution. I have just two comments:

1. The current formula exceeds the page margin. You can reduce the length of the arrow and shorten the description. Instead of "predicted mean count," write "Predicted value."

Screenshot 2024-12-04 at 11 24 34

2. Instead of `mu_hat`, use `y_hat`, and instead of "observed count," change it to "Actual value." This will align with the standards used in the previous formulas.

**Comment by sergeihychko** [comment]
Thank you for letting me know. I made the update, and the changes to align with the page width and standardized terminology are now in the second commit showing in the pull request.

**Comment by santiviquez** [comment]
Awesome, thanks!

**Pull request merged**
