### PR TITLE
Added Conversion Rate metric

### PR DESCRIPTION
**Pull request by kasthuri7903**
I've completed the Conversion Rate metric section and am open to any feedback, changes, or further assistance.

### CODE REVIEW

**Comment by santiviquez** [comment]
Thanks for this! I modified the formula a bit.

In terms of content, I think it's missing some context about the role of this metric in machine learning.

For example, in e-commerce, if a machine learning model recommends products, the conversion rate is the percentage of users who make a purchase after receiving a recommendation.

Let’s say we have models trained to predict which users are most likely to convert. These predictions are then used to target users with personalized content or offers. A high conversion rate typically indicates that the model is effective at identifying relevant users or delivering the right recommendations.

Regarding the strengths and weaknesses section, I find it a bit shallow. Here are some suggestions:

Strengths:

* Clear Performance Indicator: It provides a direct, measurable way to assess the effectiveness of a machine learning model, marketing campaign, or recommendation system.
* Versatile: It can be applied across various domains such as e-commerce, online advertising, and product recommendations, making it a universal metric for tracking success.

Weaknesses:

* Ignores User Engagement: The conversion rate doesn’t account for positive engagement that doesn’t lead to immediate conversions.
* Bias Toward Short-Term Actions: Optimizing for conversion rate can sometimes lead to short-term wins at the expense of user experience.

**Comment by santiviquez** [comment]
Hi @kasthuri7903, thank you for this! Great job.

Would you like to continue working on the second page of this metric? Have you considered ways to visualize it?

**Comment by kasthuri7903** [comment]
Hi @santiviquez  any suggestion on what to add on the second page?

**Comment by kasthuri7903** [comment]
Hi @santiviquez,
I’d like to continue working on the Conversion Rate metric, especially its visualization. I’m starting fresh and would love to hear your suggestions.

**Pull request merged**
